server:
  port: 8083
  servlet:
    context-path: /websocket

spring:
  application:
    name: websocket

  datasource:
    url: jdbc:mysql://10.206.148.20:3306/intelligent_community?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
#  redis:
#    host: 10.206.142.160
#    password: Test%123
#    port: 6379
#    database: 0

mybatis-plus:
  mapper-locations:
    classpath*:mapper/*.xml, classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

fdfs:
  so-timeout: 1500 #socket连接超时时长
  connect-timeout: 600 #连接tracker服务器超时时长
  thumb-image: #缩略图生成参数，可选
    width: 150
    height: 150
  tracker-list: 10.206.142.205:22122

sensitiveword:
  fileurl: C:/Users/chent69/Desktop/dictionary.txt


